<?php 
	// Import ACF 
	if(function_exists("register_field_group"))
	{
		register_field_group(array (
			'id' => 'acf_additional-sections',
			'title' => 'Additional Sections',
			'fields' => array (
				array (
					'key' => 'field_56f9a8e790376',
					'label' => 'Additional Sections',
					'name' => 'additional_sections',
					'type' => 'repeater',
					'sub_fields' => array (
						array (
							'key' => 'field_56f9a8f290377',
							'label' => 'Title',
							'name' => 'title',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_56f9a8fd90378',
							'label' => 'Content',
							'name' => 'content',
							'type' => 'wysiwyg',
							'column_width' => '',
							'default_value' => '',
							'toolbar' => 'full',
							'media_upload' => 'yes',
						),
					),
					'row_min' => '',
					'row_limit' => '',
					'layout' => 'table',
					'button_label' => 'Add Row',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page',
						'operator' => '==',
						'value' => '10',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_consolidating-and-leasing',
			'title' => 'Consolidating and Leasing',
			'fields' => array (
				array (
					'key' => 'field_56f9a583c0645',
					'label' => 'From To Steps',
					'name' => 'from_to_steps',
					'type' => 'repeater',
					'sub_fields' => array (
						array (
							'key' => 'field_56f9a5abc0646',
							'label' => 'From',
							'name' => 'from',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_56f9a5b3c0647',
							'label' => 'To',
							'name' => 'to',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
					),
					'row_min' => '',
					'row_limit' => '',
					'layout' => 'table',
					'button_label' => 'Add Row',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page',
						'operator' => '==',
						'value' => '4',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_frequently-asked-questions',
			'title' => 'Frequently Asked Questions',
			'fields' => array (
				array (
					'key' => 'field_56f9abea3c62d',
					'label' => 'FAQs',
					'name' => 'faqs',
					'type' => 'repeater',
					'sub_fields' => array (
						array (
							'key' => 'field_56f9ac063c62e',
							'label' => 'Question',
							'name' => 'question',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_56f9ac183c62f',
							'label' => 'Answer',
							'name' => 'answer',
							'type' => 'wysiwyg',
							'column_width' => '',
							'default_value' => '',
							'toolbar' => 'basic',
							'media_upload' => 'no',
						),
					),
					'row_min' => '',
					'row_limit' => '',
					'layout' => 'row',
					'button_label' => 'Add FAQ',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page',
						'operator' => '==',
						'value' => '17',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
					0 => 'excerpt',
					1 => 'custom_fields',
					2 => 'discussion',
					3 => 'comments',
					4 => 'revisions',
					5 => 'slug',
					6 => 'author',
					7 => 'format',
					8 => 'featured_image',
					9 => 'categories',
					10 => 'tags',
					11 => 'send-trackbacks',
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_home-page-hero',
			'title' => 'Home Page Hero',
			'fields' => array (
				array (
					'key' => 'field_56f4624e3aa04',
					'label' => 'Slider',
					'name' => '',
					'type' => 'tab',
				),
				array (
					'key' => 'field_56f4625a3aa05',
					'label' => 'Banner Image',
					'name' => 'banner_image',
					'type' => 'image',
					'save_format' => 'object',
					'preview_size' => 'thumbnail',
					'library' => 'all',
				),
				array (
					'key' => 'field_56f4628b3aa06',
					'label' => 'Sub Heading',
					'name' => 'sub_heading',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_56f462983aa07',
					'label' => 'Call To Action Text',
					'name' => 'call_to_action_text',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_56f462b73aa08',
					'label' => 'Call To Action Link',
					'name' => 'call_to_action_link',
					'type' => 'page_link',
					'post_type' => array (
						0 => 'all',
					),
					'allow_null' => 0,
					'multiple' => 0,
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'options_page',
						'operator' => '==',
						'value' => 'acf-options',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_our-process',
			'title' => 'Our Process',
			'fields' => array (
				array (
					'key' => 'field_56f9a649881a3',
					'label' => 'Steps',
					'name' => 'steps',
					'type' => 'repeater',
					'sub_fields' => array (
						array (
							'key' => 'field_56f9a658881a4',
							'label' => 'Name',
							'name' => 'name',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
						array (
							'key' => 'field_56f9a66a881a5',
							'label' => 'Short Description',
							'name' => 'short_description',
							'type' => 'textarea',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'formatting' => 'br',
						),
						array (
							'key' => 'field_56f9a674881a6',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'column_width' => '',
							'save_format' => 'object',
							'preview_size' => 'thumbnail',
							'library' => 'all',
						),
					),
					'row_min' => '',
					'row_limit' => '',
					'layout' => 'row',
					'button_label' => 'Add Row',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page',
						'operator' => '==',
						'value' => '10',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_partners',
			'title' => 'Partners',
			'fields' => array (
				array (
					'key' => 'field_56f9ab7694c9e',
					'label' => 'Partners',
					'name' => 'partners',
					'type' => 'repeater',
					'sub_fields' => array (
						array (
							'key' => 'field_56f9ab8394c9f',
							'label' => 'Logo',
							'name' => 'logo',
							'type' => 'image',
							'column_width' => '',
							'save_format' => 'object',
							'preview_size' => 'thumbnail',
							'library' => 'all',
						),
						array (
							'key' => 'field_56f9ab9194ca0',
							'label' => 'Description',
							'name' => 'description',
							'type' => 'wysiwyg',
							'column_width' => '',
							'default_value' => '',
							'toolbar' => 'basic',
							'media_upload' => 'yes',
						),
						array (
							'key' => 'field_56f9aba994ca1',
							'label' => 'Url',
							'name' => 'url',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
					),
					'row_min' => '',
					'row_limit' => '',
					'layout' => 'table',
					'button_label' => 'Add Partner',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page',
						'operator' => '==',
						'value' => '15',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_press',
			'title' => 'Press',
			'fields' => array (
				array (
					'key' => 'field_56f4653d24e19',
					'label' => 'Publisher',
					'name' => 'publisher',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_56f46571a5575',
					'label' => 'Url',
					'name' => 'url',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
				array (
					'key' => 'field_56f4654a24e1a',
					'label' => 'Date Published',
					'name' => 'date_published',
					'type' => 'text',
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'formatting' => 'html',
					'maxlength' => '',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'post_type',
						'operator' => '==',
						'value' => 'post',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
					0 => 'permalink',
					1 => 'the_content',
					2 => 'excerpt',
					3 => 'custom_fields',
					4 => 'discussion',
					5 => 'comments',
					6 => 'revisions',
					7 => 'slug',
					8 => 'author',
					9 => 'format',
					10 => 'featured_image',
					11 => 'categories',
					12 => 'tags',
					13 => 'send-trackbacks',
				),
			),
			'menu_order' => 0,
		));
		register_field_group(array (
			'id' => 'acf_strategic-partnerships',
			'title' => 'Strategic Partnerships',
			'fields' => array (
				array (
					'key' => 'field_56f46495f681c',
					'label' => 'Companies',
					'name' => 'companies',
					'type' => 'repeater',
					'sub_fields' => array (
						array (
							'key' => 'field_56f464aff681d',
							'label' => 'Logo',
							'name' => 'logo',
							'type' => 'image',
							'column_width' => '',
							'save_format' => 'object',
							'preview_size' => 'thumbnail',
							'library' => 'all',
						),
						array (
							'key' => 'field_56f464bdf681e',
							'label' => 'Description',
							'name' => 'description',
							'type' => 'textarea',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'maxlength' => '',
							'rows' => '',
							'formatting' => 'br',
						),
						array (
							'key' => 'field_56f464d2f681f',
							'label' => 'URL',
							'name' => 'url',
							'type' => 'text',
							'column_width' => '',
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'formatting' => 'html',
							'maxlength' => '',
						),
					),
					'row_min' => 0,
					'row_limit' => '',
					'layout' => 'table',
					'button_label' => 'Add Row',
				),
			),
			'location' => array (
				array (
					array (
						'param' => 'page',
						'operator' => '==',
						'value' => '15',
						'order_no' => 0,
						'group_no' => 0,
					),
				),
			),
			'options' => array (
				'position' => 'normal',
				'layout' => 'no_box',
				'hide_on_screen' => array (
				),
			),
			'menu_order' => 0,
		));
	}

 ?>