<?php
	// add_action('init', 'custom_post_types');

	// function custom_post_types(){
	// 	register_post_type('member', array(
	//       'label' => 'Members',
	//       'description' => 'Members',
	//       'public' => true,
	//       'show_ui' => true,
	//       'exclude_from_search' => false,
	//       'show_in_menu' => true,
	//       '_builtin' => false,
	//       'capability_type' => 'post',
	//       'hierarchical' => false,
	//       'rewrite' => array("slug" => "members"),
	//       'query_var' => true,
	//       'menu_icon'   => 'dashicons-businessman',
	//       'hierarchical' => false,
	//       'has_archive' => true,
	//       'supports' => array(
	//       	'title',
	//       	'page-attributes',
	//       	'editor',
	//       	'thumbnail'
	//       ),
	//       'labels' => array (
	//         'name' => 'Members',
	//         'singular_name' => 'Members',
	//         'menu_name' => 'Members',
	//         'add_new' => 'Add Member',
	//         'add_new_item' => 'Add New Member',
	//         'edit' => 'Edit',
	//         'edit_item' => 'Edit Member',
	//         'new_item' => 'New Member',
	//         'view' => 'View Member',
	//         'view_item' => 'View Member',
	//         'search_items' => 'Search Member',
	//         'not_found' => 'No Members Found',
	//         'not_found_in_trash' => 'No Members Found in Trash',
	//       ),
	//     )
	//   );
	// 	register_post_type('initiatives', array(
	//       'label' => 'Initiatives',
	//       'description' => 'Initiatives',
	//       'public' => true,
	//       'show_ui' => true,
	//       'exclude_from_search' => false,
	//       'show_in_menu' => true,
	//       '_builtin' => false,
	//       'capability_type' => 'post',
	//       'hierarchical' => false,
	//       'rewrite' => array("slug" => "initiatives"),
	//       'query_var' => true,
	//       'menu_icon'   => 'dashicons-megaphone',
	//       'hierarchical' => false,
	//       'has_archive' => true,
	//       'supports' => array('title','page-attributes', 'editor', 'thumbnail'),
	//       'labels' => array (
	//         'name' => 'Initiatives',
	//         'singular_name' => 'Initiatives',
	//         'menu_name' => 'Initiatives',
	//         'add_new' => 'Add Initiative',
	//         'add_new_item' => 'Add New Initiative',
	//         'edit' => 'Edit',
	//         'edit_item' => 'Edit Initiative',
	//         'new_item' => 'New Initiative',
	//         'view' => 'View Initiative',
	//         'view_item' => 'View Initiative',
	//         'search_items' => 'Search Initiatives',
	//         'not_found' => 'No Initiatives Found',
	//         'not_found_in_trash' => 'No Initiatives Found in Trash',
	//       ),
	//     )
	//   );
		// register_post_type('program', array(
	  //     'label' => 'Programs',
	  //     'description' => 'Programs',
	  //     'public' => true,
	  //     'show_ui' => true,
	  //     'exclude_from_search' => false,
	  //     'show_in_menu' => true,
	  //     '_builtin' => false,
	  //     'capability_type' => 'post',
	  //     'hierarchical' => false,
	  //     'rewrite' => array("slug" => "programs"),
	  //     'query_var' => true,
	  //     'menu_icon'   => 'dashicons-calendar-alt',
	  //     'hierarchical' => false,
	  //     'has_archive' => true,
	  //     'supports' => array('title','page-attributes', 'editor', 'thumbnail'),
	  //     'labels' => array (
	  //       'name' => 'Programs',
	  //       'singular_name' => 'Program',
	  //       'menu_name' => 'Programs',
	  //       'add_new' => 'Add Program',
	  //       'add_new_item' => 'Add New Program',
	  //       'edit' => 'Edit',
	  //       'edit_item' => 'Edit Program',
	  //       'new_item' => 'New Program',
	  //       'view' => 'View Program',
	  //       'view_item' => 'View Program',
	  //       'search_items' => 'Search Programs',
	  //       'not_found' => 'No Programs Found',
	  //       'not_found_in_trash' => 'No Programs Found in Trash',
	  //     ),
	  //   )
	  // );

	// }
?>
